repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-json
    -   id: trailing-whitespace
        files: \.(py|sh|yaml|txt)$
    -   id: requirements-txt-fixer
    -   id: check-xml
    -   id: debug-statements
        files: \.py$
        exclude: core/scripts/*
    -   id: end-of-file-fixer
        files: \.(py|sh)$
    -   id: flake8  # flake8 catch not used variables
        files: \.py$
        args: ['--ignore=E128,W503,E501']
    -   id: name-tests-test
        files: tests/.+\.py$
        args: ['--django']  # Use args: ['--django'] to match test*.py instead.
        exclude: mixins*
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--line-length=88, --safe]
